baseurl = "https://ghoveoud.ir"
title = "Mobin Ghoveoud"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
    pagerSize = 10

[markup.highlight]
    style = "github-dark"

[markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[params]
    author = "Mobin Ghoveoud"
    info = "Software Engineer | Backend Developer"
    description = "Mobin Ghoveoud's personal website"
    keywords = "mobin,ghoveoud,software,engineer,backend,developer,personal,python,django"
    avatarurl = "images/avatar.jpg"

    faviconSVG = "/images/favicon.ico"
    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    since = 2020

    enableTwemoji = true

    colorScheme = "dark"
    hidecolorschemetoggle = false

    customCSS = ["css/blog-list.css", "css/toc.css"]
    tableOfContents = true

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/mobinghoveoud/"

[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/mobin-ghoveoud/"

[[params.social]]
    name = "Email"
    icon = "fa-solid fa-envelope fa-2x"
    weight = 5
    url = "mailto:mobin.sgh@gmail.com"
    rel = "me"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url = "blog/"
